# Generated by Django 5.2 on 2025-06-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_option',
            field=models.CharField(blank=True, choices=[('exchange', 'Exchange')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
