# Generated by Django 5.2 on 2025-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
